name: flutter_todo_app
description: "A modern, professional Todo application built with Flutter using Clean Architecture principles."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Networking (for future cloud sync)
  dio: ^5.3.2
  connectivity_plus: ^5.0.1

  # UI & Utilities
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  lottie: ^2.7.0
  shimmer: ^3.0.0
  share_plus: ^7.2.1

  # Date & Time
  intl: ^0.19.0

  # Validation
  formz: ^0.6.1

  # Logging
  logger: ^2.0.2

  # Utils
  equatable: ^2.0.5
  uuid: ^4.1.0
  collection: ^1.18.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1
  freezed: ^2.4.6
  json_serialization: ^6.7.1

  # Testing
  bloc_test: ^9.1.4
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700