name: flutter_weather_app
description: "A simple and modern weather application built with Flutter."
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # For internationalization
    sdk: flutter
  intl: ^0.20.2

  # UI & UX
  cupertino_icons: ^1.0.6 # Default iOS icons
  google_fonts: ^6.1.0 # For custom fonts

  # State Management
  provider: ^6.1.1 # A wrapper around InheritedWidget to make them easier to use and more reusable.

  # Networking
  http: ^1.2.0 # For making HTTP requests to the weather API

  # Location
  geolocator: ^12.0.0 # For fetching device's current location

  # Data Persistence (for theme preference)
  shared_preferences: ^2.2.3

  # For comparing dates without time component
  collection: ^1.18.0
  logger: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Helps catch common coding mistakes

flutter:
  uses-material-design: true
  generate: true # Enables generation of l10n files

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An example of adding fonts from package dependencies:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
